var paper=new Palette("pad"),menuBtn=document.getElementById("menuBtn"),menu=document.getElementById("menu"),saveBtn=document.getElementById("saveBtn"),helpBtn=document.getElementById("helpBtn"),closeBtn=document.getElementById("closeBtn"),help=document.getElementById("help"),helpCloseBtn=document.getElementById("helpCloseBtn"),presetSelect=document.getElementById("presetSelect"),waveSelect=document.getElementById("waveSelect"),oscDetuneLabel=document.getElementById("oscDetuneLabel"),oscDetuneRange=
document.getElementById("oscDetuneRange"),filterSelect=document.getElementById("filterSelect"),filterFrequencyLabel=document.getElementById("filterFrequencyLabel"),filterFrequencyRange=document.getElementById("filterFrequencyRange"),filterQualityLabel=document.getElementById("filterQualityLabel"),filterQualityRange=document.getElementById("filterQualityRange"),filterGainLabel=document.getElementById("filterGainLabel"),filterGainRange=document.getElementById("filterGainRange"),delayTimeLabel=document.getElementById("delayTimeLabel"),
delayTimeRange=document.getElementById("delayTimeRange"),delayFeedbackLabel=document.getElementById("delayFeedbackLabel"),delayFeedbackRange=document.getElementById("delayFeedbackRange"),spectrumColor1=document.getElementById("spectrumColor1"),spectrumColor2=document.getElementById("spectrumColor2"),spectrumSize=document.getElementById("spectrumSize"),osccollapsible=document.getElementById("osc-collapsible"),filtercollapsible=document.getElementById("filter-collapsible"),delaycollapsible=document.getElementById("delay-collapsible"),
optionscollapsible=document.getElementById("options-collapsible");function toFixed(a,b){b=b||0;var c=0>a,d=Math.pow(10,b);a=Math.round(a*d);var e=String((c?Math.ceil:Math.floor)(a/d)),c=String((c?-a:a)%d),d=Array(Math.max(b-c.length,0)+1).join("0");return b?e+"."+d+c:e}var util={};
function adaptScreen(){util.docHeight=Math.max(document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);util.docWidth=Math.max(document.body.offsetWidth,document.documentElement.offsetWidth,document.body.clientWidth,document.documentElement.clientWidth);util.maxSpectrumHeight=3*(util.docHeight/4);paper.size(util.docWidth,util.docHeight);paper.gradient(0,0,util.docWidth,0,spectrumColor1.value,spectrumColor2.value)}adaptScreen();
window.addEventListener("resize",adaptScreen,!1);null===localStorage.getItem("userPresets")&&(localStorage.userPresets=JSON.stringify({presets:[]}));var presets=[];function loadPresets(){presets=factoryPresets.concat(JSON.parse(localStorage.userPresets).presets);for(var a="",b=0;b<presets.length;b++)a+='<option value="'+b+'">'+presets[b].name+"</option>",console.log(JSON.stringify(presets[b]));presetSelect.innerHTML=a}loadPresets();
function drawSpectrum(a){paper.clear(0,0,util.docWidth,util.docHeight);for(var b=util.docWidth/(2*a.length),c=0;c<a.length;c++)paper.rect(c*2*b,util.docHeight-util.maxSpectrumHeight*a[c]/256,b,util.docHeight)}menuBtn.addEventListener("click",function(){menu.hidden=!1;menuBtn.hidden=!0},!1);helpBtn.addEventListener("click",function(){help.hidden=!1},!1);closeBtn.addEventListener("click",function(){menu.hidden=!0;menuBtn.hidden=!1},!1);
helpCloseBtn.addEventListener("click",function(){help.hidden=!0},!1);document.getElementById("osc-title").addEventListener("click",function(){osccollapsible.hidden=!osccollapsible.hidden},!1);document.getElementById("filter-title").addEventListener("click",function(){filtercollapsible.hidden=!filtercollapsible.hidden},!1);document.getElementById("delay-title").addEventListener("click",function(){delaycollapsible.hidden=!delaycollapsible.hidden},!1);
document.getElementById("options-title").addEventListener("click",function(){optionscollapsible.hidden=!optionscollapsible.hidden},!1);
function configurePreset(a){nodes.touchOSC.type=a.osc.wave;nodes.touchOSC.detune.value=a.osc.detune;for(var b=0;b<keyNodes.length;b++)keyNodes[b].type=a.osc.wave,keyNodes[b].detune.value=a.osc.detune;nodes.filter.type=a.filter.type;nodes.filter.frequency.value=a.filter.frequency;nodes.filter.Q.value=a.filter.quality;nodes.filter.gain.value=a.filter.gain;nodes.delay.delayTime.value=a.delay.delayTime;nodes.feedback.gain.value=a.delay.feedback;waveSelect.value=a.osc.wave;oscDetuneRange.value=a.osc.detune;
oscDetuneLabel.innerHTML=a.osc.detune;filterSelect.value=a.filter.type;filterFrequencyLabel.innerHTML=toFixed(a.filter.frequency,2)+"Hz";filterQualityRange.value=a.filter.quality/30;filterQualityLabel.innerHTML=toFixed(a.filter.quality,2);filterGainRange.value=a.filter.gain;filterGainLabel.innerHTML=a.filter.gain;delayTimeRange.value=100*(a.delay.delayTime/1);delayTimeLabel.innerHTML=Math.round(1E3*a.delay.delayTime)+"ms";delayFeedbackLabel.innerHTML=Math.round(100*a.delay.feedback)}
presetSelect.addEventListener("change",function(){configurePreset(presets[presetSelect.value])},!1);
saveBtn.addEventListener("click",function(){var a={};a.name=window.prompt("Preset Name: ");a.osc={};a.osc.wave=waveSelect.value;a.osc.detune=oscDetuneRange.value;a.filter={};a.filter.type=filterSelect.value;a.filter.frequency=nodes.filter.frequency.value;a.filter.quality=nodes.filter.Q.value;a.filter.gain=nodes.filter.gain.value;a.delay={};a.delay.delayTime=nodes.delay.delayTime.value;a.delay.feedback=nodes.feedback.gain.value;var b=JSON.parse(localStorage.userPresets);b.presets.push(a);localStorage.userPresets=
JSON.stringify(b);loadPresets();presetSelect.value=presets.length-1},!1);waveSelect.addEventListener("change",function(){nodes.touchOSC.type=waveSelect.value},!1);oscDetuneRange.addEventListener("input",function(){nodes.touchOSC.detune.value=oscDetuneRange.value;for(var a=0;a<keyNodes.length;a++)keyNodes[a].detune.value=oscDetuneRange.value;oscDetuneLabel.innerHTML=oscDetuneRange.value},!1);filterSelect.addEventListener("change",function(){nodes.filter.type=filterSelect.value},!1);
filterFrequencyRange.addEventListener("input",function(){var a=context.sampleRate/2,b=Math.log(a/40)/Math.LN2,b=Math.pow(2,b*(filterFrequencyRange.value-1));nodes.filter.frequency.value=a*b;filterFrequencyLabel.innerHTML=toFixed(nodes.filter.frequency.value,2)+"Hz"},!1);filterQualityRange.addEventListener("input",function(){nodes.filter.Q.value=30*filterQualityRange.value;filterQualityLabel.innerHTML=toFixed(nodes.filter.Q.value,2)},!1);
filterGainRange.addEventListener("input",function(){nodes.filter.gain.value=filterGainRange.value;filterGainLabel.innerHTML=nodes.filter.gain.value},!1);delayTimeRange.addEventListener("input",function(){nodes.delay.delayTime.value=1*delayTimeRange.value/100;delayTimeLabel.innerHTML=Math.round(1E3*nodes.delay.delayTime.value)+"ms"},!1);
delayFeedbackRange.addEventListener("input",function(){var a=parseInt(delayFeedbackRange.value,10)/parseInt(delayFeedbackRange.max,10);nodes.feedback.gain.value=a*a;delayFeedbackLabel.innerHTML=Math.round(100*nodes.feedback.gain.value)},!1);spectrumColor1.addEventListener("change",function(){paper.gradient(0,0,util.docWidth,0,spectrumColor1.value,spectrumColor2.value)},!1);
spectrumColor2.addEventListener("change",function(){paper.gradient(0,0,util.docWidth,0,spectrumColor1.value,spectrumColor2.value)},!1);spectrumSize.addEventListener("change",function(){nodes.analyser.fftSize=spectrumSize.value},!1);var page=new Visibility({onHidden:function(){nodes.volume.gain.value=0},onVisible:function(){nodes.volume.gain.value=1}});window.screen.lockOrientation=window.screen.lockOrientation||window.screen.mozLockOrientation;window.screen.lockOrientation&&window.screen.lockOrientation("landscape");
