var paper=Raphael(0,0,"100%","100%"),menuBtn=document.getElementById("menuBtn"),menu=document.getElementById("menu"),saveBtn=document.getElementById("saveBtn"),helpBtn=document.getElementById("helpBtn"),closeBtn=document.getElementById("closeBtn"),help=document.getElementById("help"),helpCloseBtn=document.getElementById("helpCloseBtn"),presetSelect=document.getElementById("presetSelect"),waveSelect=document.getElementById("waveSelect"),oscDetuneLabel=document.getElementById("oscDetuneLabel"),oscDetuneRange=
document.getElementById("oscDetuneRange"),filterSelect=document.getElementById("filterSelect"),filterQualityLabel=document.getElementById("filterQualityLabel"),filterQualityRange=document.getElementById("filterQualityRange"),filterGainLabel=document.getElementById("filterGainLabel"),filterGainRange=document.getElementById("filterGainRange"),delayTimeLabel=document.getElementById("delayTimeLabel"),delayTimeRange=document.getElementById("delayTimeRange"),delayFeedbackLabel=document.getElementById("delayFeedbackLabel"),
delayFeedbackRange=document.getElementById("delayFeedbackRange"),spectrumSelect=document.getElementById("spectrumSelect"),osccollapsible=document.getElementById("osc-collapsible"),filtercollapsible=document.getElementById("filter-collapsible"),delaycollapsible=document.getElementById("delay-collapsible"),optionscollapsible=document.getElementById("options-collapsible");
function getDocHeight(){return Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight)}function getDocWidth(){return Math.max(document.body.scrollWidth,document.documentElement.scrollWidth,document.body.offsetWidth,document.documentElement.offsetWidth,document.body.clientWidth,document.documentElement.clientWidth)}
function toFixed(a,b){b=b||0;var c=0>a,d=Math.pow(10,b);a=Math.round(a*d);var e=String((c?Math.ceil:Math.floor)(a/d)),c=String((c?-a:a)%d),d=Array(Math.max(b-c.length,0)+1).join("0");return b?e+"."+d+c:e}var util={};util.docHeight=getDocHeight();util.docWidth=getDocWidth();util.maxSpectrumHeight=3*(util.docHeight/4);null===localStorage.getItem("userPresets")&&(localStorage.userPresets=JSON.stringify({presets:[]}));var presets=[];
function loadPresets(){presets=factoryPresets.concat(JSON.parse(localStorage.userPresets).presets);for(var a="",b=0;b<presets.length;b++)a+='<option value="'+b+'">'+presets[b].name+"</option>",console.log(JSON.stringify(presets[b]));presetSelect.innerHTML=a}loadPresets();var spectrum=[],firstTime=!0;
function drawSpectrum(a){if(firstTime){for(var b=0;b<a.length;b++)switch(spectrum[b]=paper.rect(5*b,util.docHeight,3,util.docHeight),spectrum[b].attr("stroke-width",0),spectrumSelect.value){case "1":spectrum[b].attr("fill","rgb("+b+",144,200)");break;case "2":spectrum[b].attr("fill","rgb(0,"+b+","+b+")");break;case "3":spectrum[b].attr("fill","rgb("+b+","+b+","+b+")");break;default:spectrum[b].attr("fill","rgb("+b+",144,200)")}firstTime=!1}for(b=0;b<a.length;b++)spectrum[b].attr({y:util.docHeight-
util.maxSpectrumHeight*a[b]/256})}menuBtn.onclick=function(){menu.hidden=!1;menuBtn.hidden=!0};helpBtn.onclick=function(){help.hidden=!1};closeBtn.onclick=function(){menu.hidden=!0;menuBtn.hidden=!1};helpCloseBtn.onclick=function(){help.hidden=!0};document.getElementById("osc-title").onclick=function(){osccollapsible.hidden=!osccollapsible.hidden};document.getElementById("filter-title").onclick=function(){filtercollapsible.hidden=!filtercollapsible.hidden};
document.getElementById("delay-title").onclick=function(){delaycollapsible.hidden=!delaycollapsible.hidden};document.getElementById("options-title").onclick=function(){optionscollapsible.hidden=!optionscollapsible.hidden};
presetSelect.onchange=function(){var a=presets[presetSelect.value];nodes.touchOSC.type=a.osc.wave;nodes.touchOSC.detune.value=a.osc.detune;for(var b=0;b<keyNodes.length;b++)keyNodes[b].type=a.osc.wave,keyNodes[b].detune.value=a.osc.detune;nodes.filter.type=a.filter.type;nodes.filter.frequency.value=a.filter.frequency;nodes.filter.Q.value=a.filter.quality;nodes.filter.gain.value=a.filter.gain;nodes.delay.delayTime.value=a.delay.delayTime;nodes.feedback.gain.value=a.delay.feedback;waveSelect.value=
a.osc.wave;oscDetuneRange.value=a.osc.detune;oscDetuneLabel.innerHTML=a.osc.detune;filterSelect.value=a.filter.type;filterQualityRange.value=a.filter.quality/30;filterQualityLabel.innerHTML=toFixed(a.filter.quality,2);filterGainRange.value=a.filter.gain;filterGainLabel.innerHTML=a.filter.gain;delayTimeRange.value=100*(a.delay.delayTime/1);delayTimeLabel.innerHTML=Math.round(1E3*a.delay.delayTime)+"ms";delayFeedbackLabel.innerHTML=Math.round(100*a.delay.feedback)};
saveBtn.onclick=function(){var a={};a.name=window.prompt("Preset Name: ");a.osc={};a.osc.wave=waveSelect.value;a.osc.detune=oscDetuneRange.value;a.filter={};a.filter.type=filterSelect.value;a.filter.frequency=nodes.filter.frequency.value;a.filter.quality=nodes.filter.Q.value;a.filter.gain=nodes.filter.gain.value;a.delay={};a.delay.delayTime=nodes.delay.delayTime.value;a.delay.feedback=nodes.feedback.gain.value;var b=JSON.parse(localStorage.userPresets);b.presets.push(a);localStorage.userPresets=JSON.stringify(b);
loadPresets();presetSelect.value=presets.length-1};waveSelect.onchange=function(){nodes.touchOSC.type=waveSelect.value};oscDetuneRange.oninput=function(){nodes.touchOSC.detune.value=oscDetuneRange.value;for(var a=0;a<keyNodes.length;a++)keyNodes[a].detune.value=oscDetuneRange.value;oscDetuneLabel.innerHTML=oscDetuneRange.value};filterSelect.onchange=function(){nodes.filter.type=filterSelect.value};
filterQualityRange.oninput=function(){nodes.filter.Q.value=30*filterQualityRange.value;filterQualityLabel.innerHTML=toFixed(nodes.filter.Q.value,2)};filterGainRange.oninput=function(){nodes.filter.gain.value=filterGainRange.value;filterGainLabel.innerHTML=nodes.filter.gain.value};delayTimeRange.oninput=function(){nodes.delay.delayTime.value=1*delayTimeRange.value/100;delayTimeLabel.innerHTML=Math.round(1E3*nodes.delay.delayTime.value)+"ms"};
delayFeedbackRange.oninput=function(){var a=parseInt(delayFeedbackRange.value,10)/parseInt(delayFeedbackRange.max,10);nodes.feedback.gain.value=a*a;delayFeedbackLabel.innerHTML=Math.round(100*nodes.feedback.gain.value)};
spectrumSelect.onchange=function(){for(var a=0;a<spectrum.length;a++)switch(spectrumSelect.value){case "1":spectrum[a].attr("fill","rgb("+a+",144,200)");break;case "2":spectrum[a].attr("fill","rgb(0,"+a+","+a+")");break;case "3":spectrum[a].attr("fill","rgb("+a+","+a+","+a+")");break;default:spectrum[a].attr("fill","rgb("+a+",144,200)")}};var page=new Visibility({onHidden:function(){nodes.volume.gain.value=0},onVisible:function(){nodes.volume.gain.value=1}});
